### ISSUE TITLE
inherit python3-package-ident inaccurate?

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-buildutils#5]
[Here](https://gitlab.com/poky_noty/recipes-desire/python-iot/python3-tcpclientserver) dev-branch is the actual python code: (Note it might be changing quite a bit)

[Here](https://gitlab.com/meta-layers/meta-desire/blob/master/recipes-desire/python-iot/python3-tcpclientserver_git.bb) is the recipe.

[Here](https://gitlab.com/recipes-desire/python-iot/python3-tcpclientserver/blob/master/doc/pydeps/tcpclientserver.svg) is a dependency graph calculated on the board.

and that's the output of the tool

```
####
WARNING: python3-tcpclientserver-1.0.0+gitAUTOINC+faf7904667-r0 do_package: python3-tcpclientserver uses code from python-packages:python3-io. Please add them to RDEPENDS_${PN}
WARNING: python3-tcpclientserver-1.0.0+gitAUTOINC+faf7904667-r0 do_package: python3-tcpclientserver don't use code from python-packages:python3-configparser,python3-python3. Please remove them to RDEPENDS_${PN}
####
```
which means only python-packages:python3-io is being used??? I don't see it anywhere in my graph.

just a little typo "please remove them from" not "please remove them to"

**Comment by priv-kweihmann** [comment]
Not that inaccurate as it may seem.
python3-configparser,python3-python3 do not exist: python3-configparser is part of python3-core and python3-python3 I don't know about.
python3-io does contain the code for socket, so I think this is valid too.

I personally dislike the python3-manifest-thing from poky, but what shall we do...;-)

**Comment by RobertBerger** [comment]
with another instance I followed the recommendations, but it looks like `setup.py` wants more dependencies than there are currently needed, so things are crashing in run-time.
```
WARNING: python3-localdatacollector-2.8.3+gitAUTOINC+192590e3c7-r0 do_package: python3-localdatacollector don't use code from python-packages:python3-daemonize. Please remove them to RDEPENDS_${PN}
```

if I remove it I get:

```
/ # /usr/bin/datacollector-demoExternalConfig &
/ # Traceback (most recent call last):
  File "/usr/bin/datacollector-demoExternalConfig", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'daemonize==2.4.7' distribution was not found and is required by datacollector

```
so except for `RDEPENDS`  also `setup.py` needs to be fixed.

**Comment by priv-kweihmann** [comment]
What the tool does is to scan all the packages python file for any import statement. These import are matched against the python-manifest (and additionally against site-packages) - so yes if the dependency is in the setup.py this class won't see it - But on the other hand it's not needed anyway, as there isn't an import statement in the packaged code for it.

**Comment by RobertBerger** [comment]
found another one: 
```
WARNING: python3-tcpclientserver-1.0.0+gitAUTOINC+4299eadb26-r0 do_package: python3-tcpclientserver don't use code from python-packages:python3-setuptools. Please remove them to RDEPENDS_${PN}
```

If I remove `python3-setuptools` from `RDEPENDS` I get this:
```
app-container-nmap-srv_1        | Traceback (most recent call last):
app-container-nmap-srv_1        |   File "/usr/bin/tcpclientserver-server", line 6, in <module>
app-container-nmap-srv_1        |     from pkg_resources import load_entry_point
app-container-nmap-srv_1        | ModuleNotFoundError: No module named 'pkg_resources'

```

**Comment by RobertBerger** [comment]
```
WARNING: python3-tcpclientserver-1.0.0+gitAUTOINC+4299eadb26-r0 do_package: python3-tcpclientserver don't use code from python-packages:python3-configparser,python3-setuptools. Please remove them to RDEPENDS_${PN}
```

without configparser:

```
app-container-nmap-srv_1        | Traceback (most recent call last):
app-container-nmap-srv_1        |   File "/usr/bin/tcpclientserver-server", line 6, in <module>
app-container-nmap-srv_1        |     from pkg_resources import load_entry_point
app-container-nmap-srv_1        |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
app-container-nmap-srv_1        |     @_call_aside
app-container-nmap-srv_1        |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
app-container-nmap-srv_1        |     f(*args, **kwargs)
app-container-nmap-srv_1        |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
app-container-nmap-srv_1        |     working_set = WorkingSet._build_master()
app-container-nmap-srv_1        |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
app-container-nmap-srv_1        |     ws.require(__requires__)
app-container-nmap-srv_1        |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
app-container-nmap-srv_1        |     needed = self.resolve(parse_requirements(requirements))
app-container-nmap-srv_1        |   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
app-container-nmap-srv_1        |     raise DistributionNotFound(req, requirers)
app-container-nmap-srv_1        | pkg_resources.DistributionNotFound: The 'configparser' distribution was not found and is required by tcpclientserver
```

**Comment by priv-kweihmann** [comment]
I guess I know what went wrong - current implementation does only pick pure python file "*.py" for checking not the shell-wrapper files - Reopen.
I'll try to fix this

**Comment by RobertBerger** [comment]
Hehe sorry for being picky. I hope it helps to report the bugs to improve things. I followed the output of the tool by the book and my Python person was kind of lost in space why things stopped working;) All of the things we do are open source, so they are available in public. I guess once things settle a bit I can provide a script which downloads all the layers and configure things. Just need to merge a few things from various experiments.

**Comment by priv-kweihmann** [comment]
It's all cool - I really appreciate the effort you put into my stuff.
And your right a nifty little bug in hidden somewhere here... I'll try to catch it.

**Comment by priv-kweihmann** [comment]
So even the shell wrapper should be checked - If this isn't working please reopen.
Thanks for being so picky, else wise I wouldn't have found this issue
